version: '3'
services:
  twitter:
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - ACCESS_TOKEN
      - ACCESS_TOKEN_SECRET
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    build: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
