"""empty message

Revision ID: ca7203270757
Revises: 
Create Date: 2019-06-30 22:02:35.129839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7203270757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('screen_name', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets',
    sa.Column('id_str', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_str')
    )
    op.create_table('user_followers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'follower_id')
    )
    op.create_table('hashtags',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('indices', sa.Text(), nullable=True),
    sa.Column('tweet_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id_str'], ),
    sa.PrimaryKeyConstraint('text', 'tweet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashtags')
    op.drop_table('user_followers')
    op.drop_table('tweets')
    op.drop_table('users')
    # ### end Alembic commands ###
